import { pgTable, text, timestamp, integer, boolean, uuid, jsonb, uniqueIndex, index, type AnyPgColumn } from "drizzle-orm/pg-core";

const id = () => uuid("id").defaultRandom().primaryKey();
const created = () => timestamp("created_at", { withTimezone: true }).defaultNow().notNull();

export const workspaces = pgTable("workspaces", { id: id(), name: text("name").notNull().default("Personal workspace"), timezone: text("timezone").notNull().default("America/New_York"), createdAt: created() });
export const teams = pgTable("teams", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), name: text("name").notNull(), brief: text("brief").notNull().default(""), createdAt: created() }, t => [uniqueIndex("teams_workspace_name_unique").on(t.workspaceId, t.name)]);
export const agents = pgTable("agents", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), teamId: uuid("team_id").references(() => teams.id, { onDelete: "set null" }), managerId: uuid("manager_id").references((): AnyPgColumn => agents.id, { onDelete: "set null" }), name: text("name").notNull(), role: text("role").notNull(), instructions: text("instructions").notNull().default(""), avatar: text("avatar").notNull().default("sparkles"), color: text("color").notNull().default("violet"), status: text("status").notNull().default("ACTIVE"), provider: text("provider").notNull().default("auto"), capabilities: jsonb("capabilities").$type<Record<string, unknown>>(), createdAt: created(), deletedAt: timestamp("deleted_at", { withTimezone: true }) });
export const messages = pgTable("messages", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), agentId: uuid("agent_id").notNull().references(() => agents.id, { onDelete: "cascade" }), role: text("role").notNull(), content: text("content").notNull(), kind: text("kind").notNull().default("message"), metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}), createdAt: created() });
export const routines = pgTable("routines", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), agentId: uuid("agent_id").notNull().references(() => agents.id, { onDelete: "cascade" }), name: text("name").notNull(), description: text("description").notNull(), schedule: text("schedule").notNull(), timezone: text("timezone").notNull().default("America/New_York"), enabled: boolean("enabled").notNull().default(true), icon: text("icon").notNull().default("sparkles"), lastRunAt: timestamp("last_run_at", { withTimezone: true }), nextRunAt: timestamp("next_run_at", { withTimezone: true }), lastStatus: text("last_status"), createdAt: created() }, t => [index("routines_due_index").on(t.enabled, t.nextRunAt)]);
export const runs = pgTable("runs", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), agentId: uuid("agent_id").notNull().references(() => agents.id, { onDelete: "cascade" }), routineId: uuid("routine_id").references(() => routines.id, { onDelete: "set null" }), title: text("title").notNull(), status: text("status").notNull().default("QUEUED"), summary: text("summary").notNull().default(""), idempotencyKey: text("idempotency_key"), startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(), completedAt: timestamp("completed_at", { withTimezone: true }) }, t => [uniqueIndex("runs_idempotency_unique").on(t.workspaceId, t.idempotencyKey)]);
export const runSteps = pgTable("run_steps", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), runId: uuid("run_id").notNull().references(() => runs.id, { onDelete: "cascade" }), title: text("title").notNull(), detail: text("detail").notNull().default(""), status: text("status").notNull().default("COMPLETED"), createdAt: created() });
export const approvals = pgTable("approvals", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), agentId: uuid("agent_id").notNull().references(() => agents.id, { onDelete: "cascade" }), title: text("title").notNull(), detail: text("detail").notNull(), risk: text("risk").notNull().default("WRITE"), status: text("status").notNull().default("PENDING"), createdAt: created() });
export const connections = pgTable("connections", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), agentId: uuid("agent_id").notNull().references(() => agents.id, { onDelete: "cascade" }), slug: text("slug").notNull(), status: text("status").notNull().default("CONNECTED"), createdAt: created() }, t => [uniqueIndex("connections_agent_slug_unique").on(t.agentId, t.slug)]);
export const sandboxes = pgTable("sandboxes", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), agentId: uuid("agent_id").notNull().references(() => agents.id, { onDelete: "cascade" }).unique(), provider: text("provider").notNull().default("local"), status: text("status").notNull().default("PAUSED"), minutesUsed: integer("minutes_used").notNull().default(0), createdAt: created() });
export const events = pgTable("events", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), agentId: uuid("agent_id"), type: text("type").notNull(), detail: text("detail").notNull().default(""), createdAt: created() });
export const modelUsage = pgTable("model_usage", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), provider: text("provider").notNull(), day: text("day").notNull(), calls: integer("calls").notNull().default(0), inputTokens: integer("input_tokens").notNull().default(0), outputTokens: integer("output_tokens").notNull().default(0), estimated: boolean("estimated").notNull().default(true), createdAt: created() }, t => [uniqueIndex("model_usage_workspace_provider_day_unique").on(t.workspaceId, t.provider, t.day)]);
/** One agent asking another on the user's behalf. Every row is a real model call, so it is auditable and counted. */
export const delegations = pgTable("delegations", { id: id(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), messageId: uuid("message_id"), fromAgentId: uuid("from_agent_id").notNull().references(() => agents.id, { onDelete: "cascade" }), toAgentId: uuid("to_agent_id").notNull().references(() => agents.id, { onDelete: "cascade" }), mode: text("mode").notNull().default("consult"), question: text("question").notNull(), answer: text("answer").notNull().default(""), model: text("model").notNull().default(""), inputTokens: integer("input_tokens").notNull().default(0), outputTokens: integer("output_tokens").notNull().default(0), createdAt: created() });
